In [35]:
import numpy as np

A = np.array ([[0, 1],
               [2, 3],
               [4, 5]])

B = np.array ([[0, 1, 2, 3],
               [4, 5, 6, 7]])

np.dot(A, B)
print(np.dot(A, B))

np.max(A)
print("Aの要素の最大値:", np.max(A))

np.max(B)
print("Bの要素の最大値:", np.max(B))


[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
Aの要素の最大値: 5
Bの要素の最大値: 7
